/* generated by Svelte v3.59.2 */
"use strict";

const { add_attribute, create_ssr_component, escape } = require("svelte/internal");

const css = {
	code: "h1.svelte-o015nm{color:purple}",
	map: "{\"version\":3,\"sources\":[\"\"],\"sourcesContent\":[\"<script>\\r\\n    export let name;\\r\\n    export let language;\\r\\n</script>\\r\\n\\r\\n<svelte:head>\\r\\n    <meta name= \\\"name\\\" content=name>\\r\\n    <title>{name}</title>\\r\\n</svelte:head>\\r\\n\\r\\n<h1>Hello {name}, I speak {language}</h1>\\r\\n\\r\\n<label><input bind:value = {name} /></label>\\r\\n\\r\\n<style>\\r\\n    h1 {\\r\\n        color: purple;\\r\\n    }\\r\\n</style>\\r\\n\\r\\n\"],\"names\":[],\"mappings\":\"AAeI,gBAAG,CACC,KAAK,CAAE,MACX\"}"
};

const Component = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { name } = $$props;
	let { language } = $$props;
	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);
	if ($$props.language === void 0 && $$bindings.language && language !== void 0) $$bindings.language(language);
	$$result.css.add(css);

	return `${($$result.head += '<!-- HEAD_svelte-csh9yx_START -->' + `<meta name="name" content="name">${($$result.title = `<title>${escape(name)}</title>`, "")}` + '<!-- HEAD_svelte-csh9yx_END -->', "")}

<h1 class="svelte-o015nm">Hello ${escape(name)}, I speak ${escape(language)}</h1>

<label><input${add_attribute("value", name, 0)}></label>`;
});

exports.default = Component;