/* generated by Svelte v3.59.2 */
"use strict";

const { SvelteComponent, detach, element, init, insert, noop, safe_not_equal } = require("xxx/internal");

function create_fragment(ctx) {
	let div;

	return {
		c() {
			div = element("div");
			div.textContent = `%%NAME%%:  ${name}`;
		},
		m(target, anchor) {
			insert(target, div, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div);
		}
	};
}

let name = "special";

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

exports.default = Component;